# Jekyll configuration for GitHub Pages
remote_theme: mmistakes/minimal-mistakes
title: Sajeeraa's Portfolio & Blog
description: Learning in public. Technical writing on cybersecurity.
url: "https://sajeeraa-nave.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
